AWSTemplateFormatVersion: '2010-09-09'
Description: Sunrin Managed IAM cross-account access template

Parameters:
  OrganizationName:
    Type: String
    Description: Name of the Sunrin customer organisation (no spaces).
    MinLength: 3
    MaxLength: 32
    AllowedPattern: '^[A-Za-z0-9-_]{3,32}$'
  ExternalId:
    Type: String
    Description: ExternalId provided by Sunrin (32-64 char random string)
    MinLength: 32
    MaxLength: 64
    NoEcho: true
  SunrinApiKey:
    Type: String
    Description: API key issued by Sunrin during organisation registration.
    NoEcho: true
Resources:
  SunrinPowerUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SunrinPowerUser
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::628897991799:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess

  SunrinValidationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SunrinPowerUserRole
    Properties:
      TemplateURL: 'https://juany-temp.s3.ap-northeast-2.amazonaws.com/sunrin/validation-stack.yaml'
      TimeoutInMinutes: 10
      Parameters:
        OrganizationName: !Ref OrganizationName
        ApiKey: !Ref SunrinApiKey

Outputs:
  SunrinPowerUserRoleArn:
    Description: ARN for the Sunrin power-user role
    Value: !GetAtt SunrinPowerUserRole.Arn
  DeploymentRegion:
    Description: Region this template was deployed in
    Value: !Ref AWS::Region
  DeploymentAccountId:
    Description: Account ID where this template was deployed
    Value: !Ref AWS::AccountId
